[package]
name = "megamorse_proc_macro"
description = "The procedural macro crate for the megamorse library."
license.workspace = true
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[lib]
proc-macro = true
